
import PlaygroundContent from "./components/PlaygroundContent";

export const metadata = {
    title: "MiMo Playground | Self-Evolving Website",
    description: "Experimental playground content generated by AI",
};

export default function MiMoPlaygroundPage() {
    return (
        <div className="container mx-auto px-4 py-8">
            <PlaygroundContent />
        </div>
    );
}
